ALTER TABLE consultas ADD COLUMN IF NOT EXISTS estado VARCHAR(30);
UPDATE consultas SET estado = 'PENDIENTE' WHERE estado IS NULL;
ALTER TABLE consultas ALTER COLUMN estado SET DEFAULT 'PENDIENTE';
ALTER TABLE consultas ALTER COLUMN estado SET NOT NULL;
