spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=INFO
server.servlet.session.cookie.secure=true
server.error.include-message=never
server.error.include-stacktrace=never
