spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false

server.forward-headers-strategy=framework
server.error.include-message=never
server.error.include-stacktrace=never

logging.level.root=INFO
logging.level.org.hibernate.SQL=INFO
server.servlet.session.timeout=8h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
